In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import numpy as np

In [2]:
from torchsummary import summary


In [19]:
m = nn.InstanceNorm2d(1, affine=True)

In [12]:
input = torch.Tensor([
    [[1, 2, 3], [3, 4, 5], [5, 6, 7]],
    [[1, 2, 3], [3, 4, 5], [14, 6, 7]],
    [[1, 2, 3], [3, 4, 5], [23, 6, 7]]
    ])

In [20]:
print(input)
m(input)

tensor([[[ 1.,  2.,  3.],
         [ 3.,  4.,  5.],
         [ 5.,  6.,  7.]],

        [[ 1.,  2.,  3.],
         [ 3.,  4.,  5.],
         [14.,  6.,  7.]],

        [[ 1.,  2.,  3.],
         [ 3.,  4.,  5.],
         [23.,  6.,  7.]]])


RuntimeError: weight should contain 3 elements not 1

In [18]:
print(a)
m(a)

tensor([[[[1., 1.],
          [1., 1.]],

         [[2., 2.],
          [2., 2.]],

         [[2., 2.],
          [2., 2.]]]])


tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]], grad_fn=<ViewBackward0>)

In [17]:
a = np.ones((1, 3, 2, 2))
a[0, 1]*=2
a[0, 2]*=-1
a[0, 2]+=3
a = torch.Tensor(a)

In [23]:
res = []
in_path = "data/pressure/pic/"
outpath = "../sashas_net/data/presure/pic/one_piece.npy"
for filename in os.listdir(in_path):
    res.append(np.load(os.path.join(in_path, filename)))
res = np.concatenate(res)
np.save(outpath, res)